// Writes the top facts to memory/mem0-context.md for agent startup injection

import fs from "fs";
import path from "path";
import os from "os";
import { getAllFacts, searchMemory } from "./memory.js";

const CONTEXT_FILE = path.join(os.homedir(), ".openclaw-sherra", "projects", "memory", "mem0-context.md");

export async function writeContextFile() {
  const facts = getAllFacts(0.65);

  if (facts.length === 0) {
    fs.writeFileSync(CONTEXT_FILE, "# mem0 Context\n\n_No facts extracted yet._\n");
    return;
  }

  const goals = facts.filter(f => f.fact_type === "goal");
  const prefs = facts.filter(f => f.fact_type === "preference");
  const explicit = facts.filter(f => f.fact_type === "explicit");
  const corrections = facts.filter(f => f.fact_type === "correction");
  const inferred = facts.filter(f => f.fact_type === "inferred");

  const lines: string[] = [
    "# mem0 Context",
    `_Auto-generated by mem0 at ${new Date().toISOString()}_`,
    `_${facts.length} active facts stored_`,
    "",
  ];

  function section(title: string, items: typeof facts) {
    if (items.length === 0) return;
    lines.push(`## ${title}`);
    for (const f of items.slice(0, 12)) {
      const conf = (f.confidence * 100).toFixed(0);
      const count = f.extraction_count > 1 ? ` (×${f.extraction_count})` : "";
      lines.push(`- ${f.fact} _(${conf}%${count})_`);
    }
    lines.push("");
  }

  section("Goals", goals);
  section("Preferences", prefs);
  section("Explicit Facts", explicit);
  section("Corrections", corrections);
  section("Inferred", inferred);

  fs.mkdirSync(path.dirname(CONTEXT_FILE), { recursive: true });
  fs.writeFileSync(CONTEXT_FILE, lines.join("\n"));
  console.log(`Wrote ${facts.length} facts to ${CONTEXT_FILE}`);
}
